[project]
name = "audio-separation-nodes-comfyui"
description = "Nodes:AudioSeparation, AudioCrop, AudioCombine, AudioTempoMatch."
version = "1.0.0"
license = "LICENSE"
dependencies = ["librosa==0.10.2", "numpy", "torchaudio>=2.3.0", "transformers"]

[project.urls]
Repository = "https://github.com/christian-byrne/audio-separation-nodes-comfyui"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "christian-byrne"
DisplayName = "audio-separation-nodes-comfyui"
Icon = ""
